baseURL = "oliviahuang.netlify.com"
languageCode = "en-us"
title = ""
logo = "logo-03.png"
theme = "hugo-lodi-theme"
#googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Olivia Huang Website"
    description_photo = "olivia.png"
    favicon = "icon-01.png"
    logo = "logo-03.png"
    email = "Olivia.Huang.2018@marshall.usc.edu"
    twitter = "Olivia_Huang18"
    linkedin = "www.linkedin.com/in/olivia-huang-1aba49106"
    
[params.nav]
    enable = true
    
[params.hero]
    enable = true
    avatar = "olivia.png"
    subtitle = "Olivia Huang"
    hero_right = [
    "**Hi! I'm Olivia. I am currently a MS Business Analytics student at the University of Southern California.**",
    "Previously, I studied Mathematics/Economics at the University of California, Los Angeles, with a minor in Entrepreneurship. I'm passionate about telling data-driven stories and all things data.",
    "Some of my favorite data blogs to follow and draw inspiration from are [Information is Beautiful](https://informationisbeautiful.net/) and [ThePudding] (https://pudding.cool/). I am intrigued by design thinking and beautiful visuals.", 
    "This is my [GitHub](https://github.com/oliviahuang2018)",
    "Feel free to contact me! Say hi on Twitter [@Olivia_Huang2018](https://twitter.com/Olivia_Huang18)"
    ]
    
    resume = "OliviaHuang.pdf"

[params.process]
    enable = true
    title = "Background"
    subtitle = "Data Enthusiast"
    
    
[params.case_studies]
    enable = true
    title = "Projects"
    subtitle = "Selected Works"

[params.footer]
    enable = true
